-- ---------
-- Functions
	-- Block of code => code resuable
	-- code redable
	-- pre-defined function
-- --------------------
-- There are three category of functions
	-- scalar funcntions: operate on a single value and return a single value. 
		-- string functions, numeric functions, date functions
		-- conversion functions, logical functions, miscellaneous
	-- aggregate functions: operate on a set of values and return a single value. 
		-- Eg. SUM(), AVG(), COUNT(), MAX(), MIN() etc.
	-- multi line functions: operate on multiple lines and return a single value. 
		-- Eg. GROUP_CONCAT(), JSON_ARRAYAGG() etc.
-- --------------------
-- string function : Todays topic
-- --------------------
-- Types of function 
    -- 1. Aggregate Func
	-- 2. Scalar Func
		-- String function
		-- Numeric Function
		-- DateTime Func
	-- 3. Conversion Functions: Converts data from one type to another Eg.[CAST(), CONVERT()]
    -- 4. Control Flow Func
	-- 5. Window Functions
	-- 6. User-Defined Functions (UDFs)
    -- 7. JASON Func 8. XML Functions etc.
