-- ---------
-- Functions
	-- Block of code => code resuable
	-- code redable
	-- pre-defined function
-- --------------------
-- There are two category of functions
	-- scalar func
	-- multi line functions
-- --------------------
-- string function : Todays topic
-- --------------------
-- Types of function 
    -- 1. Aggregate Func
	-- 2. Scalar Func
		-- String function
		-- Numeric Function
		-- DateTime Func
	-- 3. Conversion Functions: Converts data from one type to another Eg.[CAST(), CONVERT()]
    -- 4. Control Flow Func
	-- 5. Window Functions
	-- 6. User-Defined Functions (UDFs)
    -- 7. JASON Func 8. XML Functions etc.
